# Generated by Django 5.1.2 on 2024-10-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exemplemodel',
            old_name='est_active',
            new_name='est_disponible',
        ),
        migrations.RenameField(
            model_name='exemplemodel',
            old_name='age',
            new_name='quantité',
        ),
    ]
